### PR TITLE
Travel Module

### PR DESCRIPTION
**Pull request by miketrethewey**
Add a bunch of Hearthstones
Mages have assloads of Teleports

### CODE REVIEW

**Comment by miketrethewey** [comment]
Resolves Mikeprod/XIV_Databar#27

**Comment by Vicious-wow** [comment]
I was actually in the process of rewriting a bunch of stuff of the travel module as, from playing the game, it seems quite obvious there's a bunch of things wrong with it. I hope it's understandable that I will take a while to merge this pull request since I want to make sure nothing gets broken since you've changed a lot of lines. Thank you for your help.

**Comment by miketrethewey** [comment]
Yep! The logic is a bit convoluted and could probably be simplified. My goal was to build a db of reasonable objects with different data that only theoretically needed to be developed once. Getting something on both buttons if there were no cooled spells was a trick.
Made the most sense to me but did definitely need a lot of edits.

**Comment by Vicious-wow** [comment]
Decided I will look over the travel module myself and will not be merging this. I need to be more consequent in only allowing PRs that can actually be merged and are complete. No offense.

**Pull request closed without merging**
