### PR TITLE
Support Secondaries in bar

### PR DESCRIPTION
**Pull request by miketrethewey**
Default to ? if no icon defined

### CODE REVIEW

**Comment by miketrethewey** [comment]
Resolves Mikeprod/XIV_Databar#75
Works on Mikeprod/XIV_Databar#76

**Comment by Vicious-wow** [comment]
I'm not sure I want something like this in the main branch as it would make the bar way too busy imo. The secondaries aren't used that often in a way where you have to open their spellbook anyway, and their level information is provided in the tooltip.
However, I am going to implement this feature after adding config options to select which professions should appear in the bar, with the default being just the 2 main professions. This way everyone can decide for themselves, which is more valuable than my personal opinion on the matter.

**Comment by Vicious-wow** [comment]
Your solution is incomplete and just sets the groundwork but doesn't actually support more bars in the profession frame. I've already added the config options in my local version and will upload the solution you had intended with this merge in the main branch when it's ready.

**Comment by miketrethewey** [comment]
Excellent. Does this need any more input from me or is it being filed under "implemented differently"?
I'm good either way. :D

**Comment by Vicious-wow** [comment]
I'll adjust things and "implement it differently". The final product is going to allow the user to display first, second and cooking profession. All 3 together, just 2 of them or just 1 of them via configuration in the XIV options.

**Pull request closed without merging**
